### ISSUE TITLE
Directly use postcard and handle deserialization

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/trussed-rsa-backend#1]
In light of the postcard upgrade issues with Trussed, I think we should make two changes:
- Instead of using the postcard version re-exported by Trussed, use postcard directly.
- Instead of letting the user deserialize the data, provide a `RsaPublicParts::deserialize` method.  The serialization format should not be part of the public API but just an implementation detail of this crate.

**Comment by sosthene-nitrokey** [comment]
Done in 20ba7b72c9ea5cc43f2fd2205b8fa64e24504e75
